'use strict';(function(t){"object"==typeof exports&&"object"==typeof module?t(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],t):t(CodeMirror)})(function(t){t.defineMode("javascript",function(Ja,w){function p(a,c,b){P=a;U=b;return c}function D(a,c){var b=a.next();if('"'==b||"'"==b)return c.tokenize=Ka(b),c.tokenize(a,c);if("."==b&&a.match(/^\d[\d_]*(?:[eE][+\-]?[\d_]+)?/))return p("number","number");if("."==b&&a.match(".."))return p("spread",
"meta");if(/[\[\]{}\(\),;:\.]/.test(b))return p(b);if("="==b&&a.eat(">"))return p("=>","operator");if("0"==b&&a.match(/^(?:x[\dA-Fa-f_]+|o[0-7_]+|b[01_]+)n?/))return p("number","number");if(/\d/.test(b))return a.match(/^[\d_]*(?:n|(?:\.[\d_]*)?(?:[eE][+\-]?[\d_]+)?)?/),p("number","number");if("/"==b){if(a.eat("*"))return c.tokenize=V,V(a,c);if(a.eat("/"))return a.skipToEnd(),p("comment","comment");if(qa(a,c,1)){a:for(var d=c=!1;null!=(b=a.next());){if(!c){if("/"==b&&!d)break a;"["==b?d=!0:d&&"]"==
b&&(d=!1)}c=!c&&"\\"==b}a.match(/^\b(([gimyus])(?![gimyus]*\2))+\b/);return p("regexp","string-2")}a.eat("=");return p("operator","operator",a.current())}if("`"==b)return c.tokenize=fa,fa(a,c);if("#"==b)return a.skipToEnd(),p("error","error");if("<"==b&&a.match("!--")||"-"==b&&a.match("->"))return a.skipToEnd(),p("comment","comment");if(ra.test(b))return">"==b&&c.lexical&&">"==c.lexical.type||(a.eat("=")?"!"!=b&&"="!=b||a.eat("="):/[<>*+\-]/.test(b)&&(a.eat(b),">"==b&&a.eat(b))),p("operator","operator",
a.current());if(ha.test(b)){a.eatWhile(ha);b=a.current();if("."!=c.lastType){if(sa.propertyIsEnumerable(b))return a=sa[b],p(a.type,a.style,b);if("async"==b&&a.match(/^(\s|\/\*.*?\*\/)*[\[\(\w]/,!1))return p("async","keyword",b)}return p("variable","variable",b)}}function Ka(a){return function(c,b){var d=!1,u;if(W&&"@"==c.peek()&&c.match(La))return b.tokenize=D,p("jsonld-keyword","meta");for(;null!=(u=c.next())&&(u!=a||d);)d=!d&&"\\"==u;d||(b.tokenize=D);return p("string","string")}}function V(a,c){for(var b=
!1,d;d=a.next();){if("/"==d&&b){c.tokenize=D;break}b="*"==d}return p("comment","comment")}function fa(a,c){for(var b=!1,d;null!=(d=a.next());){if(!b&&("`"==d||"$"==d&&a.eat("{"))){c.tokenize=D;break}b=!b&&"\\"==d}return p("quasi","string-2",a.current())}function ja(a,c){c.fatArrowAt&&(c.fatArrowAt=null);var b=a.string.indexOf("=>",a.start);if(!(0>b)){if(m){var d=/:\s*(?:\w+(?:<[^>]*>|\[\])?|\{[^}]*\})\s*$/.exec(a.string.slice(a.start,b));d&&(b=d.index)}d=0;var g=!1;for(--b;0<=b;--b){var e=a.string.charAt(b),
f="([{}])".indexOf(e);if(0<=f&&3>f){if(!d){++b;break}if(0==--d){"("==e&&(g=!0);break}}else if(3<=f&&6>f)++d;else if(ha.test(e))g=!0;else if(/["'\/`]/.test(e))for(;;--b){if(0==b)return;if(a.string.charAt(b-1)==e&&"\\"!=a.string.charAt(b-2)){b--;break}}else if(g&&!d){++b;break}}g&&!d&&(c.fatArrowAt=b)}}function ta(a,c,b,d,g,e){this.indented=a;this.column=c;this.type=b;this.prev=g;this.info=e;null!=d&&(this.align=d)}function f(){for(var a=arguments.length-1;0<=a;a--)d.cc.push(arguments[a])}function b(){f.apply(null,
arguments);return!0}function ka(a,c){for(;c;c=c.next)if(c.name==a)return!0;return!1}function H(a){var c=d.state;d.marked="def";if(c.context)if("var"==c.lexical.info&&c.context&&c.context.block){var b=ua(a,c.context);if(null!=b){c.context=b;return}}else if(!ka(a,c.localVars)){c.localVars=new Q(a,c.localVars);return}w.globalVars&&!ka(a,c.globalVars)&&(c.globalVars=new Q(a,c.globalVars))}function ua(a,c){return c?c.block?(a=ua(a,c.prev))?a==c.prev?c:new R(a,c.vars,!0):null:ka(a,c.vars)?c:new R(c.prev,
new Q(a,c.vars),!1):null}function X(a){return"public"==a||"private"==a||"protected"==a||"abstract"==a||"readonly"==a}function R(a,c,b){this.prev=a;this.vars=c;this.block=b}function Q(a,c){this.name=a;this.next=c}function I(){d.state.context=new R(d.state.context,d.state.localVars,!1);d.state.localVars=Ma}function va(){d.state.context=new R(d.state.context,d.state.localVars,!0);d.state.localVars=null}function z(){d.state.localVars=d.state.context.vars;d.state.context=d.state.context.prev}function e(a,
c){var b=function(){var b=d.state,g=b.indented;if("stat"==b.lexical.type)g=b.lexical.indented;else for(var e=b.lexical;e&&")"==e.type&&e.align;e=e.prev)g=e.indented;b.lexical=new ta(g,d.stream.column(),a,null,b.lexical,c)};b.lex=!0;return b}function g(){var a=d.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function h(a){function c(d){return d==a?b():";"==a||"}"==d||")"==d||"]"==d?f():b(c)}return c}function q(a,c){return"var"==a?b(e("vardef",
c),la,h(";"),g):"keyword a"==a?b(e("form"),ma,q,g):"keyword b"==a?b(e("form"),q,g):"keyword d"==a?d.stream.match(/^\s*$/,!1)?b():b(e("stat"),na,h(";"),g):"debugger"==a?b(h(";")):"{"==a?b(e("}"),va,Y,g,z):";"==a?b():"if"==a?("else"==d.state.lexical.info&&d.state.cc[d.state.cc.length-1]==g&&d.state.cc.pop()(),b(e("form"),ma,q,g,wa)):"function"==a?b(x):"for"==a?b(e("form"),xa,q,g):"class"==a||m&&"interface"==c?(d.marked="keyword",b(e("form","class"==a?a:c),ya,g)):"variable"==a?m&&"declare"==c?(d.marked=
"keyword",b(q)):m&&("module"==c||"enum"==c||"type"==c)&&d.stream.match(/^\s*\w/,!1)?(d.marked="keyword","enum"==c?b(za):"type"==c?b(Aa,h("operator"),n,h(";")):b(e("form"),y,h("{"),e("}"),Y,g,g)):m&&"namespace"==c?(d.marked="keyword",b(e("form"),l,q,g)):m&&"abstract"==c?(d.marked="keyword",b(q)):b(e("stat"),Na):"switch"==a?b(e("form"),ma,h("{"),e("}","switch"),va,Y,g,g,z):"case"==a?b(l,h(":")):"default"==a?b(h(":")):"catch"==a?b(e("form"),I,Oa,q,g,z):"export"==a?b(e("stat"),Pa,g):"import"==a?b(e("stat"),
Qa,g):"async"==a?b(q):"@"==c?b(l,q):f(e("stat"),l,h(";"),g)}function Oa(a){if("("==a)return b(E,h(")"))}function l(a,c){return Ba(a,c,!1)}function v(a,c){return Ba(a,c,!0)}function ma(a){return"("!=a?f():b(e(")"),l,h(")"),g)}function Ba(a,c,u){if(d.state.fatArrowAt==d.stream.start){var k=u?Ca:Da;if("("==a)return b(I,e(")"),r(E,")"),g,h("=>"),k,z);if("variable"==a)return f(I,y,h("=>"),k,z)}k=u?J:K;return Ra.hasOwnProperty(a)?b(k):"function"==a?b(x,k):"class"==a||m&&"interface"==c?(d.marked="keyword",
b(e("form"),Sa,g)):"keyword c"==a||"async"==a?b(u?v:l):"("==a?b(e(")"),na,h(")"),g,k):"operator"==a||"spread"==a?b(u?v:l):"["==a?b(e("]"),Ta,g,k):"{"==a?S(Z,"}",null,k):"quasi"==a?f(aa,k):"new"==a?b(Ua(u)):"import"==a?b(l):b()}function na(a){return a.match(/[;\}\)\],]/)?f():f(l)}function K(a,c){return","==a?b(l):J(a,c,!1)}function J(a,c,u){var k=0==u?K:J,ia=0==u?l:v;if("=>"==a)return b(I,u?Ca:Da,z);if("operator"==a)return/\+\+|--/.test(c)||m&&"!"==c?b(k):m&&"<"==c&&d.stream.match(/^([^>]|<.*?>)*>\s*\(/,
!1)?b(e(">"),r(n,">"),g,k):"?"==c?b(l,h(":"),ia):b(ia);if("quasi"==a)return f(aa,k);if(";"!=a){if("("==a)return S(v,")","call",k);if("."==a)return b(Va,k);if("["==a)return b(e("]"),na,h("]"),g,k);if(m&&"as"==c)return d.marked="keyword",b(n,k);if("regexp"==a)return d.state.lastType=d.marked="operator",d.stream.backUp(d.stream.pos-d.stream.start-1),b(ia)}}function aa(a,c){return"quasi"!=a?f():"${"!=c.slice(c.length-2)?b(aa):b(l,Wa)}function Wa(a){if("}"==a)return d.marked="string-2",d.state.tokenize=
fa,b(aa)}function Da(a){ja(d.stream,d.state);return f("{"==a?q:l)}function Ca(a){ja(d.stream,d.state);return f("{"==a?q:v)}function Ua(a){return function(c){return"."==c?b(a?Xa:Ya):"variable"==c&&m?b(Za,a?J:K):f(a?v:l)}}function Ya(a,c){if("target"==c)return d.marked="keyword",b(K)}function Xa(a,c){if("target"==c)return d.marked="keyword",b(J)}function Na(a){return":"==a?b(g,q):f(K,h(";"),g)}function Va(a){if("variable"==a)return d.marked="property",b()}function Z(a,c){if("async"==a)return d.marked=
"property",b(Z);if("variable"==a||"keyword"==d.style){d.marked="property";if("get"==c||"set"==c)return b($a);var e;m&&d.state.fatArrowAt==d.stream.start&&(e=d.stream.match(/^\s*:\s*/,!1))&&(d.state.fatArrowAt=d.stream.pos+e[0].length);return b(F)}if("number"==a||"string"==a)return d.marked=W?"property":d.style+" property",b(F);if("jsonld-keyword"==a)return b(F);if(m&&X(c))return d.marked="keyword",b(Z);if("["==a)return b(l,L,h("]"),F);if("spread"==a)return b(v,F);if("*"==c)return d.marked="keyword",
b(Z);if(":"==a)return f(F)}function $a(a){if("variable"!=a)return f(F);d.marked="property";return b(x)}function F(a){if(":"==a)return b(v);if("("==a)return f(x)}function r(a,c,e){function g(k,u){return(e?-1<e.indexOf(k):","==k)?(k=d.state.lexical,"call"==k.info&&(k.pos=(k.pos||0)+1),b(function(b,d){return b==c||d==c?f():f(a)},g)):k==c||u==c?b():e&&-1<e.indexOf(";")?f(a):b(h(c))}return function(d,e){return d==c||e==c?b():f(a,g)}}function S(a,c,f){for(var k=3;k<arguments.length;k++)d.cc.push(arguments[k]);
return b(e(c,f),r(a,c),g)}function Y(a){return"}"==a?b():f(q,Y)}function L(a,c){if(m){if(":"==a)return b(n);if("?"==c)return b(L)}}function ab(a,c){if(m&&(":"==a||"in"==c))return b(n)}function Ea(a){if(m&&":"==a)return d.stream.match(/^\s*\w+\s+is\b/,!1)?b(l,bb,n):b(n)}function bb(a,c){if("is"==c)return d.marked="keyword",b()}function n(a,c){if("keyof"==c||"typeof"==c||"infer"==c)return d.marked="keyword",b("typeof"==c?v:n);if("variable"==a||"void"==c)return d.marked="type",b(B);if("|"==c||"&"==c)return b(n);
if("string"==a||"number"==a||"atom"==a)return b(B);if("["==a)return b(e("]"),r(n,"]",","),g,B);if("{"==a)return b(e("}"),r(T,"}",",;"),g,B);if("("==a)return b(r(oa,")"),cb,B);if("<"==a)return b(r(n,">"),n)}function cb(a){if("=>"==a)return b(n)}function T(a,c){if("variable"==a||"keyword"==d.style)return d.marked="property",b(T);if("?"==c||"number"==a||"string"==a)return b(T);if(":"==a)return b(n);if("["==a)return b(h("variable"),ab,h("]"),T);if("("==a)return f(M,T)}function oa(a,c){return"variable"==
a&&d.stream.match(/^\s*[?:]/,!1)||"?"==c?b(oa):":"==a?b(n):"spread"==a?b(oa):f(n)}function B(a,c){if("<"==c)return b(e(">"),r(n,">"),g,B);if("|"==c||"."==a||"&"==c)return b(n);if("["==a)return b(n,h("]"),B);if("extends"==c||"implements"==c)return d.marked="keyword",b(n);if("?"==c)return b(n,h(":"),n)}function Za(a,c){if("<"==c)return b(e(">"),r(n,">"),g,B)}function ba(){return f(n,db)}function db(a,c){if("="==c)return b(n)}function la(a,c){return"enum"==c?(d.marked="keyword",b(za)):f(y,L,C,eb)}function y(a,
c){if(m&&X(c))return d.marked="keyword",b(y);if("variable"==a)return H(c),b();if("spread"==a)return b(y);if("["==a)return S(fb,"]");if("{"==a)return S(Fa,"}")}function Fa(a,c){if("variable"==a&&!d.stream.match(/^\s*:/,!1))return H(c),b(C);"variable"==a&&(d.marked="property");return"spread"==a?b(y):"}"==a?f():"["==a?b(l,h("]"),h(":"),Fa):b(h(":"),y,C)}function fb(){return f(y,C)}function C(a,c){if("="==c)return b(v)}function eb(a){if(","==a)return b(la)}function wa(a,c){if("keyword b"==a&&"else"==
c)return b(e("form","else"),q,g)}function xa(a,c){if("await"==c)return b(xa);if("("==a)return b(e(")"),gb,g)}function gb(a){return"var"==a?b(la,N):"variable"==a?b(N):f(N)}function N(a,c){return")"==a?b():";"==a?b(N):"in"==c||"of"==c?(d.marked="keyword",b(l,N)):f(l,N)}function x(a,c){if("*"==c)return d.marked="keyword",b(x);if("variable"==a)return H(c),b(x);if("("==a)return b(I,e(")"),r(E,")"),g,Ea,q,z);if(m&&"<"==c)return b(e(">"),r(ba,">"),g,x)}function M(a,c){if("*"==c)return d.marked="keyword",
b(M);if("variable"==a)return H(c),b(M);if("("==a)return b(I,e(")"),r(E,")"),g,Ea,z);if(m&&"<"==c)return b(e(">"),r(ba,">"),g,M)}function Aa(a,c){if("keyword"==a||"variable"==a)return d.marked="type",b(Aa);if("<"==c)return b(e(">"),r(ba,">"),g)}function E(a,c){"@"==c&&b(l,E);return"spread"==a?b(E):m&&X(c)?(d.marked="keyword",b(E)):m&&"this"==a?b(L,C):f(y,L,C)}function Sa(a,c){return"variable"==a?ya(a,c):ca(a,c)}function ya(a,c){if("variable"==a)return H(c),b(ca)}function ca(a,c){if("<"==c)return b(e(">"),
r(ba,">"),g,ca);if("extends"==c||"implements"==c||m&&","==a)return"implements"==c&&(d.marked="keyword"),b(m?n:l,ca);if("{"==a)return b(e("}"),A,g)}function A(a,c){if("async"==a||"variable"==a&&("static"==c||"get"==c||"set"==c||m&&X(c))&&d.stream.match(/^\s+[\w$\xa1-\uffff]/,!1))return d.marked="keyword",b(A);if("variable"==a||"keyword"==d.style)return d.marked="property",b(m?da:x,A);if("number"==a||"string"==a)return b(m?da:x,A);if("["==a)return b(l,L,h("]"),m?da:x,A);if("*"==c)return d.marked="keyword",
b(A);if(m&&"("==a)return f(M,A);if(";"==a||","==a)return b(A);if("}"==a)return b();if("@"==c)return b(l,A)}function da(a,c){if("?"==c)return b(da);if(":"==a)return b(n,C);if("="==c)return b(v);a=d.state.lexical.prev;return f(a&&"interface"==a.info?M:x)}function Pa(a,c){return"*"==c?(d.marked="keyword",b(pa,h(";"))):"default"==c?(d.marked="keyword",b(l,h(";"))):"{"==a?b(r(Ga,"}"),pa,h(";")):f(q)}function Ga(a,c){if("as"==c)return d.marked="keyword",b(h("variable"));if("variable"==a)return f(v,Ga)}
function Qa(a){return"string"==a?b():"("==a?f(l):f(ea,Ha,pa)}function ea(a,c){if("{"==a)return S(ea,"}");"variable"==a&&H(c);"*"==c&&(d.marked="keyword");return b(hb)}function Ha(a){if(","==a)return b(ea,Ha)}function hb(a,c){if("as"==c)return d.marked="keyword",b(ea)}function pa(a,c){if("from"==c)return d.marked="keyword",b(l)}function Ta(a){return"]"==a?b():f(r(v,"]"))}function za(){return f(e("form"),y,h("{"),e("}"),r(ib,"}"),g,g)}function ib(){return f(y,C)}function qa(a,c,b){return c.tokenize==
D&&/^(?:operator|sof|keyword [bcd]|case|new|export|default|spread|[\[{}\(,;:]|=>)$/.test(c.lastType)||"quasi"==c.lastType&&/\{\s*$/.test(a.string.slice(0,a.pos-(b||0)))}var O=Ja.indentUnit,Ia=w.statementIndent,W=w.jsonld,G=w.json||W,m=w.typescript,ha=w.wordCharacters||/[\w$\xa1-\uffff]/,sa=function(){function a(a){return{type:a,style:"keyword"}}var b=a("keyword a"),d=a("keyword b"),e=a("keyword c"),g=a("keyword d"),f=a("operator"),h={type:"atom",style:"atom"};return{"if":a("if"),"while":b,"with":b,
"else":d,"do":d,"try":d,"finally":d,"return":g,"break":g,"continue":g,"new":a("new"),"delete":e,"void":e,"throw":e,"debugger":a("debugger"),"var":a("var"),"const":a("var"),let:a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),"switch":a("switch"),"case":a("case"),"default":a("default"),"in":f,"typeof":f,"instanceof":f,"true":h,"false":h,"null":h,undefined:h,NaN:h,Infinity:h,"this":a("this"),"class":a("class"),"super":a("atom"),yield:e,"export":a("export"),"import":a("import"),"extends":e,
await:e}}(),ra=/[+\-*&%=<>!?|~^@]/,La=/^@(context|id|value|language|type|container|list|set|reverse|index|base|vocab|graph)"/,P,U,Ra={atom:!0,number:!0,variable:!0,string:!0,regexp:!0,"this":!0,"jsonld-keyword":!0},d={state:null,column:null,marked:null,cc:null},Ma=new Q("this",new Q("arguments",null));z.lex=!0;g.lex=!0;return{startState:function(a){a={tokenize:D,lastType:"sof",cc:[],lexical:new ta((a||0)-O,0,"block",!1),localVars:w.localVars,context:w.localVars&&new R(null,null,!1),indented:a||0};
w.globalVars&&"object"==typeof w.globalVars&&(a.globalVars=w.globalVars);return a},token:function(a,b){a.sol()&&(b.lexical.hasOwnProperty("align")||(b.lexical.align=!1),b.indented=a.indentation(),ja(a,b));if(b.tokenize!=V&&a.eatSpace())return null;var c=b.tokenize(a,b);if("comment"==P)return c;b.lastType="operator"!=P||"++"!=U&&"--"!=U?P:"incdec";a:{var e=P,g=U,f=b.cc;d.state=b;d.stream=a;d.marked=null;d.cc=f;d.style=c;b.lexical.hasOwnProperty("align")||(b.lexical.align=!0);for(;;)if((f.length?f.pop():
G?l:q)(e,g)){for(;f.length&&f[f.length-1].lex;)f.pop()();if(d.marked){c=d.marked;break a}if(a="variable"==e)b:{for(a=b.localVars;a;a=a.next)if(a.name==g){a=!0;break b}for(b=b.context;b;b=b.prev)for(a=b.vars;a;a=a.next)if(a.name==g){a=!0;break b}a=void 0}if(a){c="variable-2";break a}break a}}return c},indent:function(a,b){if(a.tokenize==V)return t.Pass;if(a.tokenize!=D)return 0;var c=b&&b.charAt(0),d=a.lexical,e;if(!/^\s*else\b/.test(b))for(var f=a.cc.length-1;0<=f;--f){var h=a.cc[f];if(h==g)d=d.prev;
else if(h!=wa)break}for(;!("stat"!=d.type&&"form"!=d.type||"}"!=c&&(!(e=a.cc[a.cc.length-1])||e!=K&&e!=J||/^[,\.=+\-*:?[\(]/.test(b)));)d=d.prev;Ia&&")"==d.type&&"stat"==d.prev.type&&(d=d.prev);e=d.type;f=c==e;return"vardef"==e?d.indented+("operator"==a.lastType||","==a.lastType?d.info.length+1:0):"form"==e&&"{"==c?d.indented:"form"==e?d.indented+O:"stat"==e?(c=d.indented,a="operator"==a.lastType||","==a.lastType||ra.test(b.charAt(0))||/[,.]/.test(b.charAt(0)),c+(a?Ia||O:0)):"switch"!=d.info||f||
0==w.doubleIndentSwitch?d.align?d.column+(f?0:1):d.indented+(f?0:O):d.indented+(/^(?:case|default)\b/.test(b)?O:2*O)},electricInput:/^\s*(?:case .*?:|default:|\{|\})$/,blockCommentStart:G?null:"/*",blockCommentEnd:G?null:"*/",blockCommentContinue:G?null:" * ",lineComment:G?null:"//",fold:"brace",closeBrackets:"()[]{}''\"\"``",helperType:G?"json":"javascript",jsonldMode:W,jsonMode:G,expressionAllowed:qa,skipExpression:function(a){var b=a.cc[a.cc.length-1];b!=l&&b!=v||a.cc.pop()}}});t.registerHelper("wordChars",
"javascript",/[\w$]/);t.defineMIME("text/javascript","javascript");t.defineMIME("text/ecmascript","javascript");t.defineMIME("application/javascript","javascript");t.defineMIME("application/x-javascript","javascript");t.defineMIME("application/ecmascript","javascript");t.defineMIME("application/json",{name:"javascript",json:!0});t.defineMIME("application/x-json",{name:"javascript",json:!0});t.defineMIME("application/ld+json",{name:"javascript",jsonld:!0});t.defineMIME("text/typescript",{name:"javascript",
typescript:!0});t.defineMIME("application/typescript",{name:"javascript",typescript:!0})});
