'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Language_Pad.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1=̀
        '''2=́
        '''3=̂
        '''4=̃
        '''5=̄
        '''6=̅
        '''7=̆
        '''8=̇
        '''9=̈
        '''10=̉
        '''11=̊
        '''12=̋
        '''13=̌
        '''14=̏
        '''15=̨
        '''16=̧
        '''17=̰
        '''18=̱
        '''19=̒
        '''20=̓.
        '''</summary>
        Friend ReadOnly Property Accents() As String
            Get
                Return ResourceManager.GetString("Accents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1=t͡sʼ
        '''2=t͡ɬʼ
        '''3=c͡ʎ̝̥ʼ
        '''4=t͡ʃʼ
        '''5=ʈ͡ʂʼ
        '''6=k͡xʼ
        '''7=k͡ʟ̝̊ʼ
        '''8=q͡χʼ
        '''9=p̪͡f
        '''10=b̪͡v
        '''11=t͡s
        '''12=d͡z
        '''13=t̪͡s̪
        '''14=d̪͡z̪
        '''15=t͡θ
        '''16=d͡ð
        '''17=t͡ʃ
        '''18=d͡ʒ
        '''19=t͡ɕ
        '''20=d͡ʑ
        '''21=ʈ͡ʂ
        '''22=ɖ͡ʐ
        '''23=t͡ɬ
        '''24=d͡ɮ
        '''25=c͡ç
        '''26=ɟ͡ʝ
        '''27=c͡ʎ̝̥
        '''28=k͡x
        '''29=k͡ʟ̝̊
        '''30=ɡ͡ʟ̝
        '''31=q͡χ
        '''32=k͡p
        '''33=ɡ͡b
        '''34=ŋ͡m.
        '''</summary>
        Friend ReadOnly Property Affricates() As String
            Get
                Return ResourceManager.GetString("Affricates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Æ|æ|Œ|œ|Þ|þ|Ð|ð|Å|å|Ł|ł|Á|á|É|é|Í|í|Ó|ó|Ú|ú|Â|â|Ê|ê|Î|î|Ô|ô|Û|û|À|à|È|è|Ì|ì|Ò|ò|Ù|ù|Ã|ã|Ẽ|ẽ|Ĩ|ĩ|Õ|õ|Ũ|ũ|Ñ|ñ|Ā|ā|Ē|ē|Ī|ī|Ō|ō|Ū|ū|Ä|ä|Ë|ë|Ï|ï|Ö|ö|Ü|ü|Ą|ą|Ę|ę|Į|į|Ǫ|ǫ|Ų|ų|’.
        '''</summary>
        Friend ReadOnly Property Common() As String
            Get
                Return ResourceManager.GetString("Common", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1=m̥
        '''2=m
        '''3=ɱ
        '''4=n̥
        '''5=n
        '''6=ɳ̊
        '''7=ɳ
        '''8=ɲ̊
        '''9=ɲ
        '''10=ŋ̊
        '''11=ŋ
        '''12=ɴ
        '''13=p
        '''14=b
        '''15=p̪
        '''16=b̪
        '''17=t̪
        '''18=d̪
        '''19=t
        '''20=d
        '''21=ʈ
        '''22=ɖ
        '''23=c
        '''24=ɟ
        '''25=k
        '''26=ɡ
        '''27=q
        '''28=ɢ
        '''29=ʡ
        '''30=ʔ
        '''31=s
        '''32=z
        '''33=ʃ
        '''34=ʒ
        '''35=ʂ
        '''36=ʐ
        '''37=ɕ
        '''38=ʑ
        '''39=ɸ
        '''40=β
        '''41=f
        '''42=v
        '''43=θ
        '''44=ð
        '''45=θ̱
        '''46=ð̠
        '''47=ɹ̠̊˔
        '''48=ɹ̠˔
        '''49=ç
        '''50=ʝ
        '''51=x
        '''52=ɣ
        '''53=χ
        '''54=ʁ
        '''55=ħ
        '''56=ʕ
        '''57=ʜ
        '''58=ʢ
        '''59=h
        '''60=ɦ
        '''61=ʋ
        '''62=ɹ
        '''63=ɻ
        '''64=j̊
        '''65=j
        '''66=ɰ
        '''67=ⱱ̟
        '''68=ⱱ
        '''69=ɾ̥
        '''70=ɾ
        '''71=ɽ
        '''72=ɢ̆
        '''73=ʡ̯
        '''74=ʙ
        '''75=r̥
        '''76=r
        '''77=ɽ͡r
        '''78=ʀ̥
        '''79=ʀ
        '''80=ᴙ
        '''81=ɬ
        '''82=ɮ
        '''83=ꞎ
        '''84=	ʎ̝̊
        '''85=ʟ̝̊
        '''86=ʟ̝
        '''87=l̥
        '''88=l
        '''89=ɭ
        '''90=ʎ
        '''91=ʟ
        '''92=ɺ
        '''93=ɺ̢ 
        '''94=ʎ̯
        '''95=ʟ̆
        '''96=ʘ
        '''97=ǀ
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Consonants() As String
            Get
                Return ResourceManager.GetString("Consonants", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 		&lt;style type=&quot;text/css&quot;&gt;
        '''			table.table-style-three {
        '''				font-family: verdana, arial, sans-serif;
        '''				font-size: 11px;
        '''				color: #333333;
        '''				border-width: 1px;
        '''				border-color: #383838;
        '''				border-collapse: collapse;
        '''			}
        '''			table.table-style-three th {
        '''				border-width: 1px;
        '''				padding: 8px;
        '''				border-style: solid;
        '''				border-color: #dbdbdb;
        '''				background-color: #c2c2c2;
        '''				color: #ffffff;
        '''			}
        '''			table.table-style-three tr:hover td {
        '''				cursor: pointer;
        '''			}
        '''			table.table-st [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HtmlStyle() As String
            Get
                Return ResourceManager.GetString("HtmlStyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''	&lt;head&gt;
        '''		&lt;title&gt;{0}&lt;/title&gt;
        '''	&lt;/head&gt;
        '''	&lt;body&gt;
        '''{1}
        '''{2}
        '''	&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property HtmlTemplate() As String
            Get
                Return ResourceManager.GetString("HtmlTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Radius=0
        '''
        '''Active Colors=~225|~225
        '''Active Positions=0|1
        '''Active Angle=90
        '''Active Border Color=~173
        '''Active Text Color=$2
        '''Active Highlight Color=$0
        '''
        '''Hover Colors=#e5f1fb|#e5f1fb
        '''Hover Positions=0|1
        '''Hover Angle=90
        '''Hover Border Color=#0078d7
        '''Hover Text Color=$2
        '''Hover Highlight Color=$0
        '''
        '''Pressed Colors=#cce4f7|#cce4f7
        '''Pressed Positions=0|1
        '''Pressed Angle=90
        '''Pressed Border Color=#005499
        '''Pressed Text Color=$2
        '''Pressed Highlight Color=$0.
        '''</summary>
        Friend ReadOnly Property KeyStyle() As String
            Get
                Return ResourceManager.GetString("KeyStyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1=̩
        '''2=̯
        '''3=ʰ
        '''4=̚
        '''5=ʱ
        '''6=ⁿ	
        '''7=ˡ
        '''8=̥
        '''9=̬
        '''10=̤
        '''11=̰
        '''12=̪
        '''13=̼
        '''14=̺
        '''15=̻
        '''16=̟
        '''17=̠
        '''18=̈
        '''19=̽
        '''20=̝
        '''21=˔
        '''22=̞
        '''23=˕
        '''24=̹
        '''25=̜
        '''26=ʷ
        '''27=ʲ
        '''28=ˠ
        '''29=ˤ
        '''30=ᶣ
        '''31=̴
        '''32=̘
        '''33=̙
        '''34=̃
        '''35=˞
        '''36=ˈ
        '''37=ˌ
        '''38=ː
        '''39=ˑ
        '''40=̆
        '''41=.
        '''42=‿
        '''.
        '''</summary>
        Friend ReadOnly Property Other() As String
            Get
                Return ResourceManager.GetString("Other", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;table&gt;
        '''{0}
        '''&lt;/table&gt;.
        '''</summary>
        Friend ReadOnly Property TableTemplate() As String
            Get
                Return ResourceManager.GetString("TableTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1=|
        '''2=‖
        '''3=˥
        '''4=˦
        '''5=˧
        '''6=˨
        '''7=˩
        '''8=ꜛ
        '''9=ꜜ
        '''10=↓
        '''11=↑
        '''12=→
        '''13=↗
        '''14=↘.
        '''</summary>
        Friend ReadOnly Property ToneIntonation() As String
            Get
                Return ResourceManager.GetString("ToneIntonation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Positions=0|0.9|1
        '''Angle=90
        '''Radius=0
        '''Border Color=~171
        '''Highlight Color$0
        '''Bottom Only=1.
        '''</summary>
        Friend ReadOnly Property Top() As String
            Get
                Return ResourceManager.GetString("Top", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Transparent2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Transparent2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1=i
        '''2=y
        '''3=ɨ
        '''4=ʉ
        '''5=ɯ
        '''6=u
        '''7=ɪ
        '''8=ʏ
        '''9=ɪ̈
        '''10=ʊ̈
        '''11=ʊ
        '''12=e
        '''13=ø
        '''14=ɘ
        '''15=ɵ
        '''16=ɤ
        '''17=o
        '''18=e̞
        '''19=ø̞
        '''20=ə
        '''21=ɵ̞
        '''22=ɤ̞
        '''23=o̞
        '''24=ɛ
        '''25=œ
        '''26=ɜ
        '''27=ɞ
        '''28=ʌ
        '''29=ɔ
        '''30=æ
        '''31=ɐ
        '''32=a
        '''33=ɶ
        '''34=ä
        '''35=ɒ̈
        '''36=ɑ
        '''37=ɒ.
        '''</summary>
        Friend ReadOnly Property Vowels() As String
            Get
                Return ResourceManager.GetString("Vowels", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
