'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Language_Pad.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grave=◌̀
        '''Accute=◌́
        '''Circumflex=◌̂
        '''Tilde=◌̃
        '''Macron=◌̄
        '''Overline=◌̅
        '''Breve=◌̆
        '''Dot Above=◌̇
        '''Diaeresis/Umlaut=◌̈
        '''Hook Above=◌̉
        '''Ring Above=◌̊
        '''Double Accute=◌̋
        '''Caron/Háček=◌̌
        '''Double Grave=◌̏
        '''Ogonek=◌̨
        '''Cedilla=◌̧
        '''Tilde Below=◌̰
        '''Macron Below=◌̱
        '''Turned Comma Above=◌̒
        '''Koronis=◌̓.
        '''</summary>
        Friend ReadOnly Property Accents() As String
            Get
                Return ResourceManager.GetString("Accents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voiceless alveolar sibilant affricate=t͡s
        '''Voiced alveolar sibilant affricate=d͡z
        '''Voiceless palato-alveolar sibilant affricate=t͡ʃ
        '''Voiced palato-alveolar sibilant affricate=d͡ʒ
        '''Voiceless retroflex sibilant affricate=ʈ͡ʂ
        '''Voiced retroflex sibilant affricate=ɖ͡ʐ
        '''Voiceless alveolo-palatal sibilant affricate=t͡ɕ
        '''Voiced alveolo-palatal sibilant affricate=d͡ʑ
        '''Voiceless bilabial affricate=p͡ɸ
        '''Voiced bilabial affricate=b͡β
        '''Voiceless labiodental affricate=p̪͡f
        '''Voiced labiodental affricate=b̪͡v
        '''Voiceless dental non-sib [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Affricates() As String
            Get
                Return ResourceManager.GetString("Affricates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Okina=ʻ
        '''Saltillo=Ꞌ
        '''Ash/AE ligature=æ
        '''OE ligature=œ
        '''Thorn=þ
        '''Eth=ð
        '''A ring=å
        '''U ring=ů
        '''O slashed=ø
        '''L with stroke=ł
        '''A acute=á
        '''C acute=ć
        '''E acute=é
        '''G acute=ǵ
        '''I acute=í
        '''K acute=ḱ
        '''L acute=ĺ
        '''M acute=ḿ
        '''N acute=ń
        '''O acute=ó
        '''P acute=ṕ
        '''R acute=ŕ
        '''U acute=ú
        '''W acute=ẃ
        '''Y acute=ý
        '''Z acute=ź
        '''A circumflex=â
        '''B circumflex=ĉ
        '''E circumflex=ê 
        '''G circumflex=ĝ
        '''H circumflex=ĥ
        '''I circumflex=î
        '''J circumflex=ĵ
        '''O circumflex=ô
        '''S circumflex=ŝ
        '''U circumflex=û
        '''W circumflex=ŵ
        '''Y circumflex=ŷ
        '''Z circumflex=ẑ
        '''A grave=à
        '''E grave=è
        '''I grave=ì
        '''O grave=ò
        '''U gra [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Common() As String
            Get
                Return ResourceManager.GetString("Common", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voiceless bilabial nasal=m̥
        '''Bilabial nasal=m
        '''Labiodental nasal=ɱ
        '''Linguolabial nasal=n̼
        '''Voiceless alveolar nasal=n̥
        '''Alveolar nasal=n
        '''Voiceless retroflex nasal=ɳ̊
        '''Retroflex nasal=ɳ
        '''Voiceless palatal nasal=ɲ̊
        '''Palatal nasal=ɲ
        '''Voiceless velar nasal=ŋ̊
        '''Velar nasal=ŋ
        '''Uvular nasal=ɴ
        '''Voiceless bilabial stop=p
        '''Voiced bilabial stop=b
        '''Voiceless labiodental stop=p̪
        '''Voiced labiodental stop=b̪
        '''Voiceless linguolabial stop=t̼
        '''Voiced linguolabial stop=d̼
        '''Voiceless dental stop=t̪
        '''Voiced dental stop=d̪
        '''Voiceless alveolar stop= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Consonants() As String
            Get
                Return ResourceManager.GetString("Consonants", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voiceless below=◌̥
        '''Voiceless above=◌̊
        '''Voiced=◌̬
        '''Aspirated=◌ʰ
        '''More rounded below=◌̹
        '''More rounded above=◌͗
        '''More rounded aside=◌˒
        '''Less rounded below=◌̜
        '''Less rounded above=◌͑
        '''Less rounded aside=◌˓
        '''Advanced below=◌̟
        '''Advanced aside=◌˖
        '''Retracted below=◌̠
        '''Retracted aside=◌˗
        '''Centralized=◌̈
        '''Mid-centralized=◌̽
        '''Syllabic/Vocalic below=◌̩
        '''Syllabic/Vocalic above=◌̍
        '''Non-syllabic/Semivowel below=◌̯
        '''Non-syllabic/Semivowel above=◌̑
        '''Rhotic/R-colored=◌˞
        '''Breathy voiced=◌̤
        '''Creaky voiced=◌̰
        '''Linguolabial=◌̼
        '''Labialized=◌ʷ
        '''Palatalize [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Diacritics() As String
            Get
                Return ResourceManager.GetString("Diacritics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 		&lt;style type=&quot;text/css&quot;&gt;
        '''			body {
        '''				padding: 1em;
        '''			}
        '''
        '''			table {
        '''				width: 100%;
        '''				font-family: verdana, arial, sans-serif;
        '''				font-size: 11px;
        '''				color: #333333;
        '''				border-width: 1px;
        '''				border-color: #383838;
        '''				border-collapse: collapse;
        '''			}
        '''
        '''			table th {
        '''				border-width: 1px;
        '''				padding: 8px;
        '''				border-style: solid;
        '''				border-color: #000000;
        '''				background-color: #525252;
        '''				color: #ffffff;
        '''			}
        '''
        '''			table tr:hover td {
        '''				cursor: pointer;
        '''			}
        '''
        '''			table  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HtmlStyle() As String
            Get
                Return ResourceManager.GetString("HtmlStyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''	&lt;head&gt;
        '''		&lt;title&gt;{0}&lt;/title&gt;
        '''	&lt;/head&gt;
        '''	&lt;body&gt;
        '''		&lt;h1&gt;{0}&lt;/h1&gt;
        '''		&lt;div&gt;
        '''{1}
        '''		&lt;/div&gt;
        '''{2}
        '''{3}
        '''	&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property HtmlTemplate() As String
            Get
                Return ResourceManager.GetString("HtmlTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Radius=0
        '''
        '''Active Colors=~225|~225
        '''Active Positions=0|1
        '''Active Angle=90
        '''Active Border Color=~173
        '''Active Text Color=$2
        '''Active Highlight Color=$0
        '''
        '''Hover Colors=#e5f1fb|#e5f1fb
        '''Hover Positions=0|1
        '''Hover Angle=90
        '''Hover Border Color=#0078d7
        '''Hover Text Color=$2
        '''Hover Highlight Color=$0
        '''
        '''Pressed Colors=#cce4f7|#cce4f7
        '''Pressed Positions=0|1
        '''Pressed Angle=90
        '''Pressed Border Color=#005499
        '''Pressed Text Color=$2
        '''Pressed Highlight Color=$0.
        '''</summary>
        Friend ReadOnly Property KeyStyle() As String
            Get
                Return ResourceManager.GetString("KeyStyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Á=Á
        '''á=á
        '''Ǽ=Ǽ
        '''ǽ=ǽ
        '''Ć=Ć
        '''ć=ć
        '''É=É
        '''é=é
        '''Ǵ=Ǵ
        '''ǵ=ǵ
        '''Í=Í
        '''í=í
        '''Ḱ=Ḱ
        '''ḱ=ḱ
        '''Ĺ=Ĺ
        '''ĺ=ĺ
        '''Ḿ=Ḿ
        '''ḿ=ḿ
        '''Ń=Ń
        '''ń=ń
        '''Ó=Ó
        '''ó=ó
        '''Ṕ=Ṕ
        '''ṕ=ṕ
        '''Ŕ=Ŕ
        '''ŕ=ŕ
        '''Ś=Ś
        '''ś=ś
        '''Ú=Ú
        '''ú=ú
        '''Ẃ=Ẃ
        '''ẃ=ẃ
        '''Ý=Ý
        '''ý=ý
        '''Ź=Ź
        '''ź=ź
        '''Ő=Ő
        '''ő=ő
        '''Ű=Ű
        '''ű=ű
        '''À=À
        '''à=à
        '''È=È
        '''è=è
        '''Ì=Ì
        '''ì=ì
        '''Ǹ=Ǹ
        '''ǹ=ǹ
        '''Ò=Ò
        '''ò=ò
        '''Ù=Ù
        '''ù=ù
        '''Ỳ=Ỳ
        '''ỳ=ỳ
        '''Ȁ=Ȁ
        '''ȁ=ȁ
        '''Ȅ=Ȅ
        '''ȅ=ȅ
        '''Ȉ=Ȉ
        '''ȉ=ȉ
        '''Ȍ=Ȍ
        '''ȍ=ȍ
        '''Ȑ=Ȑ
        '''ȑ=ȑ
        '''Ȕ=Ȕ
        '''ȕ=ȕ
        '''Ă=Ă
        '''ă=ă
        '''Ĕ=Ĕ
        '''ĕ=ĕ
        '''Ğ=Ğ
        '''ğ=ğ
        '''Ĭ=Ĭ
        '''ĭ=ĭ
        '''Ŏ=Ŏ
        '''ŏ=ŏ
        '''Ŭ=Ŭ
        '''ŭ=ŭ
        '''Ȃ=Ȃ
        '''ȃ=ȃ
        '''Ȇ=Ȇ
        '''ȇ=ȇ
        '''Ȋ=Ȋ
        '''ȋ=ȋ
        '''Ȏ=Ȏ
        '''ȏ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SmartReplace() As String
            Get
                Return ResourceManager.GetString("SmartReplace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 		&lt;table&gt;
        '''{0}
        '''		&lt;/table&gt;.
        '''</summary>
        Friend ReadOnly Property TableTemplate() As String
            Get
                Return ResourceManager.GetString("TableTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1=|
        '''2=‖
        '''3=˥
        '''4=˦
        '''5=˧
        '''6=˨
        '''7=˩
        '''8=ꜛ
        '''9=ꜜ
        '''10=↓
        '''11=↑
        '''12=→
        '''13=↗
        '''14=↘.
        '''</summary>
        Friend ReadOnly Property ToneIntonation() As String
            Get
                Return ResourceManager.GetString("ToneIntonation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Positions=0|0.9|1
        '''Angle=90
        '''Radius=0
        '''Border Color=~171
        '''Highlight Color$0
        '''Bottom Only=1.
        '''</summary>
        Friend ReadOnly Property Top() As String
            Get
                Return ResourceManager.GetString("Top", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Transparent2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Transparent2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close front unrounded vowel/High front unrounded vowel=i
        '''Close front rounded vowel/High front rounded vowel=y
        '''Close front protruded vowel/High front protruded vowel=y̫
        '''Close central unrounded vowel/High central unrounded vowel=ɨ
        '''Close central rounded vowel/High central rounded vowel=ʉ
        '''Close central compressed vowel/High central compressed vowel=ÿ
        '''Close back unrounded vowel/High back unrounded vowel=ɯ
        '''Close back rounded vowel/High back rounded vowel=u
        '''Close back compressed vowel/High back compressed vowel=ɯᵝ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Vowels() As String
            Get
                Return ResourceManager.GetString("Vowels", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
