'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LangPad.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grave=◌̀
        '''Accute=◌́
        '''Circumflex=◌̂
        '''Tilde=◌̃
        '''Macron=◌̄
        '''Overline=◌̅
        '''Breve=◌̆
        '''Dot Above=◌̇
        '''Diaeresis/Umlaut=◌̈
        '''Hook Above=◌̉
        '''Ring Above=◌̊
        '''Double Accute=◌̋
        '''Caron/Háček=◌̌
        '''Double Grave=◌̏
        '''Ogonek=◌̨
        '''Cedilla=◌̧
        '''Tilde Below=◌̰
        '''Macron Below=◌̱
        '''Turned Comma Above=◌̒
        '''Koronis=◌̓.
        '''</summary>
        Friend ReadOnly Property Accents() As String
            Get
                Return ResourceManager.GetString("Accents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voiceless alveolar sibilant affricate=t͡s
        '''Voiced alveolar sibilant affricate=d͡z
        '''Voiceless palato-alveolar sibilant affricate=t͡ʃ
        '''Voiced palato-alveolar sibilant affricate=d͡ʒ
        '''Voiceless retroflex sibilant affricate=ʈ͡ʂ
        '''Voiced retroflex sibilant affricate=ɖ͡ʐ
        '''Voiceless alveolo-palatal sibilant affricate=t͡ɕ
        '''Voiced alveolo-palatal sibilant affricate=d͡ʑ
        '''Voiceless bilabial post-trilled dental stop=t̪͡ʙ̥
        '''Voiceless bilabial affricate=p͡ɸ
        '''Voiced bilabial affricate=b͡β
        '''Voiceless labiodental affricate=p̪ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Affricates() As String
            Get
                Return ResourceManager.GetString("Affricates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Okina=ʻ
        '''Saltillo=Ꞌ
        '''Ash/AE ligature=æ
        '''OE ligature=œ
        '''Thorn=þ
        '''Eth=ð
        '''A ring=å
        '''U ring=ů
        '''O slashed=ø
        '''L with stroke=ł
        '''A acute=á
        '''C acute=ć
        '''E acute=é
        '''G acute=ǵ
        '''I acute=í
        '''K acute=ḱ
        '''L acute=ĺ
        '''M acute=ḿ
        '''N acute=ń
        '''O acute=ó
        '''P acute=ṕ
        '''R acute=ŕ
        '''U acute=ú
        '''W acute=ẃ
        '''Y acute=ý
        '''Z acute=ź
        '''A circumflex=â
        '''B circumflex=ĉ
        '''E circumflex=ê 
        '''G circumflex=ĝ
        '''H circumflex=ĥ
        '''I circumflex=î
        '''J circumflex=ĵ
        '''O circumflex=ô
        '''S circumflex=ŝ
        '''U circumflex=û
        '''W circumflex=ŵ
        '''Y circumflex=ŷ
        '''Z circumflex=ẑ
        '''A grav [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Common() As String
            Get
                Return ResourceManager.GetString("Common", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voiceless bilabial nasal=m̥
        '''Bilabial nasal=m
        '''Labiodental nasal=ɱ
        '''Linguolabial nasal=n̼
        '''Voiceless alveolar nasal=n̥
        '''Alveolar nasal=n
        '''Voiceless retroflex nasal=ɳ̊
        '''Retroflex nasal=ɳ
        '''Voiceless palatal nasal=ɲ̊
        '''Palatal nasal=ɲ
        '''Voiceless velar nasal=ŋ̊
        '''Velar nasal=ŋ
        '''Uvular nasal=ɴ
        '''Voiceless bilabial stop=p
        '''Voiced bilabial stop=b
        '''Voiceless labiodental stop=p̪
        '''Voiced labiodental stop=b̪
        '''Voiceless linguolabial stop=t̼
        '''Voiced linguolabial stop=d̼
        '''Voiceless dental stop=t̪
        '''Voiced dental stop=d̪
        '''Voi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Consonants() As String
            Get
                Return ResourceManager.GetString("Consonants", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ye grave /e/=ѐ
        '''Yo /jo/=ё
        '''Dje /dʑ/=ђ
        '''Gje /dʑ/=ѓ
        '''Yest/Ukrainian Ye /je/=є
        '''Dze /dz/=ѕ
        '''Dotted I /i/=і
        '''Yi /ji/=ї
        '''Je /j/=ј
        '''Lje /ʎ/=љ
        '''Nje /ɲ/=њ
        '''Tshe /tɕ/=ћ
        '''Kje /c/=ќ
        '''I with grave /i/=ѝ
        '''Short U /w/=ў
        '''Dzhe /ɖʐ/=џ
        '''Omega /o/=ѡ
        '''Yat /æ/=ѣ
        '''Short I with tail /j̊/=ҋ
        '''Semisoft sign /◌ʲ/=ҍ
        '''Er with tick /r̥/=ҏ
        '''Ge with upturn /ɡ/=ґ
        '''Ghayn/Ge with stroke /ʁ/=ғ
        '''Ge with middle hook /ɣ/=ҕ
        '''Zhje /tʂ/, /dʑ/=җ
        '''Dhe /ð/=ҙ
        '''Ka with descender /q/=қ
        '''Ka with vertical stroke /ɟ/=ҝ
        '''Ka with stroke /qʼ/=ҟ
        '''Bashkir Qa/Ba [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Cyrillic() As String
            Get
                Return ResourceManager.GetString("Cyrillic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voiceless below=◌̥
        '''Voiceless above=◌̊
        '''Voiced=◌̬
        '''Faucalized voice=◌͈
        '''Hollow voice=◌͚
        '''Aspirated=◌ʰ
        '''Breathy voice/Murmured Voice=◌ʱ
        '''More rounded below=◌̹
        '''More rounded above=◌͗
        '''More rounded aside=◌˒
        '''Less rounded below=◌̜
        '''Less rounded above=◌͑
        '''Less rounded aside=◌˓
        '''Advanced below=◌̟
        '''Advanced aside=◌˖
        '''Retracted below=◌̠
        '''Retracted aside=◌˗
        '''Centralized=◌̈
        '''Mid-centralized=◌̽
        '''Syllabic/Vocalic below=◌̩
        '''Syllabic/Vocalic above=◌̍
        '''Non-syllabic/Semivowel below=◌̯
        '''Non-syllabic/Semivowel above=◌̑
        '''Rhot [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Diacritics() As String
            Get
                Return ResourceManager.GetString("Diacritics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kai (and)=ϗ
        '''Digamma /w/=ϝ
        '''Pamphylian Digamma /w/=ͷ
        '''Heta /h/=ͱ
        '''Koppa /k/=ϙ
        '''San /s/=Ϻ
        '''Sampi /s/=ϡ
        '''Archaic Sampi /s/=ͳ
        '''Sho /ʃ/=ϸ.
        '''</summary>
        Friend ReadOnly Property Greek() As String
            Get
                Return ResourceManager.GetString("Greek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 		&lt;style type=&quot;text/css&quot;&gt;
        '''			body {
        '''				padding: 1em;
        '''			}
        '''
        '''			table {
        '''				width: 100%;
        '''				font-family: verdana, arial, sans-serif;
        '''				font-size: 11px;
        '''				color: #333333;
        '''				border-width: 1px;
        '''				border-color: #383838;
        '''				border-collapse: collapse;
        '''			}
        '''
        '''			table th {
        '''				border-width: 1px;
        '''				padding: 8px;
        '''				border-style: solid;
        '''				border-color: #000000;
        '''				background-color: #525252;
        '''				color: #ffffff;
        '''			}
        '''
        '''			table tr:hover td {
        '''				cursor: pointer;
        '''			}
        '''
        '''			table  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HtmlStyle() As String
            Get
                Return ResourceManager.GetString("HtmlStyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''	&lt;head&gt;
        '''		&lt;meta charset=&quot;utf-8&quot;&gt;
        '''		&lt;title&gt;{0}&lt;/title&gt;
        '''	&lt;/head&gt;
        '''	&lt;body&gt;
        '''		&lt;h1&gt;{0}&lt;/h1&gt;
        '''		&lt;div&gt;
        '''{1}
        '''		&lt;/div&gt;
        '''{2}
        '''{3}
        '''	&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property HtmlTemplate() As String
            Get
                Return ResourceManager.GetString("HtmlTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''	&lt;head&gt;
        '''		&lt;meta charset=&quot;utf-8&quot;&gt;
        '''		&lt;title&gt;{0}&lt;/title&gt;
        '''	&lt;/head&gt;
        '''	&lt;body&gt;
        '''		{1}
        '''	&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property PageExportHtml() As String
            Get
                Return ResourceManager.GetString("PageExportHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Á=Á
        '''á=á
        '''Ǽ=Ǽ
        '''ǽ=ǽ
        '''Ć=Ć
        '''ć=ć
        '''É=É
        '''é=é
        '''Ǵ=Ǵ
        '''ǵ=ǵ
        '''Í=Í
        '''í=í
        '''Ḱ=Ḱ
        '''ḱ=ḱ
        '''Ĺ=Ĺ
        '''ĺ=ĺ
        '''Ḿ=Ḿ
        '''ḿ=ḿ
        '''Ń=Ń
        '''ń=ń
        '''Ó=Ó
        '''ó=ó
        '''Ṕ=Ṕ
        '''ṕ=ṕ
        '''Ŕ=Ŕ
        '''ŕ=ŕ
        '''Ś=Ś
        '''ś=ś
        '''Ú=Ú
        '''ú=ú
        '''Ẃ=Ẃ
        '''ẃ=ẃ
        '''Ý=Ý
        '''ý=ý
        '''Ź=Ź
        '''ź=ź
        '''Ő=Ő
        '''ő=ő
        '''Ű=Ű
        '''ű=ű
        '''À=À
        '''à=à
        '''È=È
        '''è=è
        '''Ì=Ì
        '''ì=ì
        '''Ǹ=Ǹ
        '''ǹ=ǹ
        '''Ò=Ò
        '''ò=ò
        '''Ù=Ù
        '''ù=ù
        '''Ỳ=Ỳ
        '''ỳ=ỳ
        '''Ȁ=Ȁ
        '''ȁ=ȁ
        '''Ȅ=Ȅ
        '''ȅ=ȅ
        '''Ȉ=Ȉ
        '''ȉ=ȉ
        '''Ȍ=Ȍ
        '''ȍ=ȍ
        '''Ȑ=Ȑ
        '''ȑ=ȑ
        '''Ȕ=Ȕ
        '''ȕ=ȕ
        '''Ă=Ă
        '''ă=ă
        '''Ĕ=Ĕ
        '''ĕ=ĕ
        '''Ğ=Ğ
        '''ğ=ğ
        '''Ĭ=Ĭ
        '''ĭ=ĭ
        '''Ŏ=Ŏ
        '''ŏ=ŏ
        '''Ŭ=Ŭ
        '''ŭ=ŭ
        '''Ȃ=Ȃ
        '''ȃ=ȃ
        '''Ȇ=Ȇ
        '''ȇ=ȇ
        '''Ȋ=Ȋ
        '''ȋ=ȋ
        '''Ȏ=Ȏ
        '''ȏ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SmartReplace() As String
            Get
                Return ResourceManager.GetString("SmartReplace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primary stress=ˈ◌
        '''Secondary stress=ˌ◌
        '''Long=◌ː
        '''Half long=◌ˑ
        '''Extra long=◌ːː
        '''Extra-short=◌̆
        '''Minor (foot) group=|
        '''Major (intonation) group=‖
        '''Syllable break=.
        '''Linking (absence of a break)=‿.
        '''</summary>
        Friend ReadOnly Property Suprasegmentals() As String
            Get
                Return ResourceManager.GetString("Suprasegmentals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 		&lt;table&gt;
        '''{0}
        '''		&lt;/table&gt;.
        '''</summary>
        Friend ReadOnly Property TableTemplate() As String
            Get
                Return ResourceManager.GetString("TableTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extra-high (top) tone diacritic=◌̋
        '''Extra-high (top) tone bar=˥
        '''High tone diacritic=◌́
        '''High tone bar=˦
        '''Mid tone diacritic=◌̄
        '''Mid tone bar=˧
        '''Low tone diacritic=◌̀
        '''Low tone bar=˨
        '''Extra-low (bottom) tone diacritic=◌̏
        '''Extra-low (bottom) tone bar=˩
        '''Rising tone diacritic=◌̌
        '''Rising tone bar=˩˥
        '''Falling tone diacritic=◌̂
        '''Falling tone bar=˥˩
        '''High rising tone diacritic=◌᷄
        '''High rising tone bar=˦˥
        '''Low rising tone diacritic=◌᷅
        '''Low rising tone bar=˩˨
        '''Rising-falling tone diacritic=◌᷈
        '''Rising-falling tone b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ToneIntonation() As String
            Get
                Return ResourceManager.GetString("ToneIntonation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Positions=0|0.9|1
        '''Angle=90
        '''Radius=0
        '''Border Color=~171
        '''Highlight Color$0
        '''Bottom Only=1.
        '''</summary>
        Friend ReadOnly Property Top() As String
            Get
                Return ResourceManager.GetString("Top", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Transparent2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Transparent2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close front unrounded vowel/High front unrounded vowel=i
        '''Close front rounded vowel/High front rounded vowel=y
        '''Close front protruded vowel/High front protruded vowel=y̫
        '''Close central unrounded vowel/High central unrounded vowel=ɨ
        '''Close central rounded vowel/High central rounded vowel=ʉ
        '''Close central compressed vowel/High central compressed vowel=ÿ
        '''Close back unrounded vowel/High back unrounded vowel=ɯ
        '''Close back rounded vowel/High back rounded vowel=u
        '''Close back compressed vowel/High back compressed  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Vowels() As String
            Get
                Return ResourceManager.GetString("Vowels", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
