//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangPadData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LangPadData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cm-s-ayu-mirage.CodeMirror{background:#1f2430;color:#cbccc6}.cm-s-ayu-mirage div.CodeMirror-selected{background:#34455a}.cm-s-ayu-mirage .CodeMirror-line::selection,.cm-s-ayu-mirage .CodeMirror-line&gt;span::selection,.cm-s-ayu-mirage .CodeMirror-line&gt;span&gt;span::selection{background:#34455a}.cm-s-ayu-mirage .CodeMirror-line::-moz-selection,.cm-s-ayu-mirage .CodeMirror-line&gt;span::-moz-selection,.cm-s-ayu-mirage .CodeMirror-line&gt;span&gt;span::-moz-selection{background:rgba(25,30,42,99)}.cm-s-ayu-mirage .CodeMirror [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ayu_mirage {
            get {
                return ResourceManager.GetString("ayu_mirage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cm-s-base16-dark.CodeMirror{background:#151515;color:#e0e0e0}.cm-s-base16-dark div.CodeMirror-selected{background:#303030}.cm-s-base16-dark .CodeMirror-line::selection,.cm-s-base16-dark .CodeMirror-line&gt;span::selection,.cm-s-base16-dark .CodeMirror-line&gt;span&gt;span::selection{background:rgba(48,48,48,.99)}.cm-s-base16-dark .CodeMirror-line::-moz-selection,.cm-s-base16-dark .CodeMirror-line&gt;span::-moz-selection,.cm-s-base16-dark .CodeMirror-line&gt;span&gt;span::-moz-selection{background:rgba(48,48,48,.99)}.cm-s-ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base16_dark {
            get {
                return ResourceManager.GetString("base16_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .CodeMirror{font-family:monospace;height:300px;color:#000;direction:ltr}.CodeMirror-lines{padding:4px 0}.CodeMirror pre.CodeMirror-line,.CodeMirror pre.CodeMirror-line-like{padding:0 4px}.CodeMirror-gutter-filler,.CodeMirror-scrollbar-filler{background-color:#fff}.CodeMirror-gutters{border-right:1px solid #ddd;background-color:#f7f7f7;white-space:nowrap}.CodeMirror-linenumber{padding:0 3px 0 5px;min-width:20px;text-align:right;color:#999;white-space:nowrap}.CodeMirror-guttermarker{color:#000}.CodeMirror-gut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeMirrorCss {
            get {
                return ResourceManager.GetString("CodeMirrorCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;use strict&apos;;var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(y,J,F){y instanceof String&amp;&amp;(y=String(y));for(var t=y.length,U=0;U&lt;t;U++){var la=y[U];if(J.call(F,la,U,y))return{i:U,v:la}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
        ///$jscomp.defineProperty=$jscomp.ASSUME_ES5||&quot;function&quot;==typeof Object.defineProperties?Object.defineProperty:function(y,J,F){y!=Array.prototype&amp;&amp;y!=Object.prototy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeMirrorJs {
            get {
                return ResourceManager.GetString("CodeMirrorJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;title&gt;{0}&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;{0}&lt;/h1&gt;
        ///		&lt;div&gt;
        ///{1}
        ///		&lt;/div&gt;
        ///{2}
        ///	&lt;table&gt;
        ///{3}
        ///	&lt;/table&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string DictionaryBase {
            get {
                return ResourceManager.GetString("DictionaryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;style type=&quot;text/css&quot;&gt;
        ///			body {
        ///				padding: 1em;
        ///			}
        ///
        ///			table {
        ///				width: 100%;
        ///				font-family: verdana, arial, sans-serif;
        ///				font-size: 11px;
        ///				color: #333333;
        ///				border-width: 1px;
        ///				border-color: #383838;
        ///				border-collapse: collapse;
        ///			}
        ///
        ///			table th {
        ///				border-width: 1px;
        ///				padding: 8px;
        ///				border-style: solid;
        ///				border-color: #000000;
        ///				background-color: #525252;
        ///				color: #ffffff;
        ///			}
        ///
        ///			table tr:hover td {
        ///				cursor: pointer;
        ///			}
        ///
        ///			table  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DictionaryStyle {
            get {
                return ResourceManager.GetString("DictionaryStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///
        ///    {DocumentStyle}
        ///    &lt;script&gt;
        ///        window.onerror = function (msg, url, linenumber) {
        ///            alert(&apos;Error message: &apos; + msg + &apos;\nURL: &apos; + url + &apos;\nLine Number: &apos; + linenumber);
        ///            return true;
        ///        }
        ///    &lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    {Content}
        ///&lt;/body&gt;
        ///&lt;/html&gt; .
        /// </summary>
        internal static string DocumentBase {
            get {
                return ResourceManager.GetString("DocumentBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {
        ///    box-sizing: border-box !important;
        ///}
        ///
        ///body {
        ///    font-family: Arial, sans-serif;
        ///}
        ///
        ///h1, h2, h3, h4, h5, h6 {
        ///    margin: 0.25rem 0;
        ///}
        ///
        ///.hidden {
        ///    display: none !important;
        ///}
        ///
        ///.inline {
        ///    display: inline !important;
        ///}
        ///
        ///.bold {
        ///    font-weight: bold;
        ///}
        ///
        ///.italic {
        ///    font-style: italic;
        ///}.
        /// </summary>
        internal static string DocumentStyle {
            get {
                return ResourceManager.GetString("DocumentStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;use strict&apos;;(function(k){&quot;object&quot;==typeof exports&amp;&amp;&quot;object&quot;==typeof module?k(require(&quot;../../lib/codemirror&quot;)):&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;../../lib/codemirror&quot;],k):k(CodeMirror)})(function(k){function l(d){for(var e={},f=0;f&lt;d.length;++f)e[d[f].toLowerCase()]=!0;return e}function m(d,e){for(var f=!1,k;null!=(k=d.next());){if(f&amp;&amp;&quot;/&quot;==k){e.tokenize=null;break}f=&quot;*&quot;==k}return[&quot;comment&quot;,&quot;comment&quot;]}k.defineMode(&quot;css&quot;,function(d,e){function f(a,c){G=c;return a}function l(a,c){var b=
        ///a.next();i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModeCss {
            get {
                return ResourceManager.GetString("ModeCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;use strict&apos;;(function(d){&quot;object&quot;==typeof exports&amp;&amp;&quot;object&quot;==typeof module?d(require(&quot;../../lib/codemirror&quot;),require(&quot;../xml/xml&quot;),require(&quot;../javascript/javascript&quot;),require(&quot;../css/css&quot;)):&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;../../lib/codemirror&quot;,&quot;../xml/xml&quot;,&quot;../javascript/javascript&quot;,&quot;../css/css&quot;],d):d(CodeMirror)})(function(d){function p(f){var c=k[f];return c?c:k[f]=new RegExp(&quot;\\s+&quot;+f+&quot;\\s*=\\s*(&apos;|\&quot;)?([^&apos;\&quot;]+)(&apos;|\&quot;)?\\s*&quot;)}function q(f,c){return(f=f.match(p(c)))?/^\s*(.*?)\s*$/.exec(f[2]) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModeHtmlMixed {
            get {
                return ResourceManager.GetString("ModeHtmlMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;use strict&apos;;(function(t){&quot;object&quot;==typeof exports&amp;&amp;&quot;object&quot;==typeof module?t(require(&quot;../../lib/codemirror&quot;)):&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;../../lib/codemirror&quot;],t):t(CodeMirror)})(function(t){t.defineMode(&quot;javascript&quot;,function(Ja,w){function p(a,c,b){P=a;U=b;return c}function D(a,c){var b=a.next();if(&apos;&quot;&apos;==b||&quot;&apos;&quot;==b)return c.tokenize=Ka(b),c.tokenize(a,c);if(&quot;.&quot;==b&amp;&amp;a.match(/^\d[\d_]*(?:[eE][+\-]?[\d_]+)?/))return p(&quot;number&quot;,&quot;number&quot;);if(&quot;.&quot;==b&amp;&amp;a.match(&quot;..&quot;))return p(&quot;spread&quot;,
        ///&quot;meta&quot;);if [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModeJavaScript {
            get {
                return ResourceManager.GetString("ModeJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;use strict&apos;;(function(g){&quot;object&quot;==typeof exports&amp;&amp;&quot;object&quot;==typeof module?g(require(&quot;../../lib/codemirror&quot;)):&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;../../lib/codemirror&quot;],g):g(CodeMirror)})(function(g){var D={autoSelfClosers:{area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,frame:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0,menuitem:!0},implicitlyClosed:{dd:!0,li:!0,optgroup:!0,option:!0,p:!0,rp:!0,rt:!0,tbody:!0,td:!0,tfoot:!0,th:!0,tr:!0},contextGrabbers: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModeXml {
            get {
                return ResourceManager.GetString("ModeXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {
        ///    box-sizing: border-box !important;
        ///}
        ///
        ///textarea {
        ///    display: block;
        ///    margin: 0 !important;
        ///    width: 100vw;
        ///    height: 100vh;
        ///    left: 0px;
        ///    top: 0px;
        ///    bottom: 0;
        ///    right: 0;
        ///    position: fixed;
        ///    border: 0px solid transparent;
        ///}
        ///
        ///body {
        ///    background: white !important;
        ///    margin: 0 !important;
        ///    padding: 0 !important;
        ///    display: block;
        ///    height: 100vh;
        ///    width: 100vw;
        ///}
        ///.
        /// </summary>
        internal static string TextEditorCss {
            get {
                return ResourceManager.GetString("TextEditorCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;&gt;
        ///    {CodeMirrorStyle}
        ///    {CodeMirrorScript}
        ///
        ///    {CodeMirrorModeCss}
        ///    {CodeMirrorModeXml}
        ///    {CodeMirrorModeJs}
        ///    {CodeMirrorModeHtmlMixed}
        ///
        ///    {CodeMirrorTheme}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;textarea id=&quot;textEdit&quot;&gt;&lt;/textarea&gt;
        ///
        ///    {TextEditStyle}
        ///    {TextEditScript}
        ///&lt;/body&gt;
        ///&lt;/html&gt; .
        /// </summary>
        internal static string TextEditorHtml {
            get {
                return ResourceManager.GetString("TextEditorHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function loadEditor(teaxAreaId) {
        ///    var textArea = document.getElementById(teaxAreaId);
        ///
        ///    var instance = CodeMirror.fromTextArea(textArea, {
        ///        mode: &quot;htmlmixed&quot;,
        ///        theme: &quot;ttcn&quot;,
        ///        lineNumbers: true,
        ///        gutter: true
        ///    });
        ///
        ///    instance.setSize(&quot;100%&quot;, &quot;100%&quot;);
        ///
        ///    return instance;
        ///}
        ///
        ///var codeMirrorInstance = loadEditor(&quot;textEdit&quot;);
        ///
        ///function setEditorTheme(themeName) {
        ///
        ///}
        ///
        ///function setEditorContent(content) {
        ///    codeMirrorInstance.setValue(content);
        ///}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextEditorJs {
            get {
                return ResourceManager.GetString("TextEditorJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cm-s-ttcn .cm-quote{color:#090}.cm-s-ttcn .cm-negative{color:#d44}.cm-s-ttcn .cm-positive{color:#292}.cm-s-ttcn .cm-header,.cm-strong{font-weight:700}.cm-s-ttcn .cm-em{font-style:italic}.cm-s-ttcn .cm-link{text-decoration:underline}.cm-s-ttcn .cm-strikethrough{text-decoration:line-through}.cm-s-ttcn .cm-header{color:#00f;font-weight:700}.cm-s-ttcn .cm-atom{color:#219}.cm-s-ttcn .cm-attribute{color:#00c}.cm-s-ttcn .cm-bracket{color:#997}.cm-s-ttcn .cm-comment{color:#333}.cm-s-ttcn .cm-def{color:#00f}.cm-s-t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ttcn {
            get {
                return ResourceManager.GetString("ttcn", resourceCulture);
            }
        }
    }
}
