//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangPadData.Properties; 
  using System;
  
  
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Resources {
      
      private static global::System.Resources.ResourceManager resourceMan;
      
      private static global::System.Globalization.CultureInfo resourceCulture;
      
      [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
      internal Resources() {
      }
      
      /// <summary>
      ///   Returns the cached ResourceManager instance used by this class.
      /// </summary>
      [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
      internal static global::System.Resources.ResourceManager ResourceManager {
          get {
              if (object.ReferenceEquals(resourceMan, null)) {
                  global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LangPadData.Properties.Resources", typeof(Resources).Assembly);
                  resourceMan = temp;
              }
              return resourceMan;
          }
      }
      
      /// <summary>
      ///   Overrides the current thread's CurrentUICulture property for all
      ///   resource lookups using this strongly typed resource class.
      /// </summary>
      [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
      internal static global::System.Globalization.CultureInfo Culture {
          get {
              return resourceCulture;
          }
          set {
              resourceCulture = value;
          }
      }
      
      /// <summary>
      ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
      ///&lt;html lang=&quot;en&quot;&gt;
      ///	&lt;head&gt;
      ///		&lt;meta charset=&quot;utf-8&quot;&gt;
      ///		&lt;title&gt;{0}&lt;/title&gt;
      ///	&lt;/head&gt;
      ///	&lt;body&gt;
      ///		&lt;h1&gt;{0}&lt;/h1&gt;
      ///		&lt;div&gt;
      ///{1}
      ///		&lt;/div&gt;
      ///{2}
      ///	&lt;table&gt;
      ///{3}
      ///	&lt;/table&gt;
      ///	&lt;/body&gt;
      ///&lt;/html&gt;.
      /// </summary>
      internal static string DictionaryHtmlBase {
          get {
              return ResourceManager.GetString("DictionaryHtmlBase", resourceCulture);
          }
      }
      
      /// <summary>
      ///   Looks up a localized string similar to 		&lt;style type=&quot;text/css&quot;&gt;
      ///			body {
      ///				padding: 1em;
      ///			}
      ///
      ///			table {
      ///				width: 100%;
      ///				font-family: verdana, arial, sans-serif;
      ///				font-size: 11px;
      ///				color: #333333;
      ///				border-width: 1px;
      ///				border-color: #383838;
      ///				border-collapse: collapse;
      ///			}
      ///
      ///			table th {
      ///				border-width: 1px;
      ///				padding: 8px;
      ///				border-style: solid;
      ///				border-color: #000000;
      ///				background-color: #525252;
      ///				color: #ffffff;
      ///			}
      ///
      ///			table tr:hover td {
      ///				cursor: pointer;
      ///			}
      ///
      ///			table  [rest of string was truncated]&quot;;.
      /// </summary>
      internal static string DictionaryHtmlStyle {
          get {
              return ResourceManager.GetString("DictionaryHtmlStyle", resourceCulture);
          }
      }
  }
